# Generated by Django 3.2.3 on 2022-04-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='song',
            field=models.FileField(default='exit', upload_to='product'),
            preserve_default=False,
        ),
    ]
