# Generated by Django 3.2.3 on 2022-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_prcategory_prproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='category')),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('cast', models.TextField(max_length=100)),
                ('up', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
