# Generated by Django 3.2.3 on 2022-05-15 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shquantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('shproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ShCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtitle', models.CharField(max_length=50, verbose_name='Category Title')),
                ('shslug', models.SlugField(max_length=55, verbose_name='Category Slug')),
                ('shdescription', models.TextField(blank=True, verbose_name='Category Description')),
                ('shcategory_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Category Image')),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'ShCategories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtitle', models.CharField(max_length=150, verbose_name='Product Title')),
                ('shslug', models.SlugField(max_length=160, verbose_name='Product Slug')),
                ('shsku', models.CharField(max_length=255, unique=True, verbose_name='Unique Product ID (SKU)')),
                ('shshort_description', models.TextField(verbose_name='Short Description')),
                ('shdetail_description', models.TextField(blank=True, null=True, verbose_name='Detail Description')),
                ('shproduct_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product Image')),
                ('shprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('shcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product Categoy')),
            ],
            options={
                'verbose_name_plural': 'ShProducts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='PrCategory',
        ),
        migrations.RemoveField(
            model_name='prproduct',
            name='prcategory',
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
        migrations.DeleteModel(
            name='PrProduct',
        ),
    ]
