# Generated by Django 3.2.3 on 2022-05-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220515_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shproduct',
            name='shcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shcategory', verbose_name='Product Categoy'),
        ),
    ]
