# Generated by Django 3.2.3 on 2022-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_shcart_shproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shproduct',
            old_name='shslug',
            new_name='slug',
        ),
    ]
