# Generated by Django 3.2.3 on 2022-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_shslug_shproduct_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='pics')),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('cast', models.TextField(max_length=100)),
                ('trailer', models.CharField(max_length=100)),
                ('up', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
