# Generated by Django 3.2.3 on 2022-05-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220517_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shcategory',
            old_name='shslug',
            new_name='slug',
        ),
    ]
