# Generated by Django 3.2.3 on 2022-05-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_shslug_shcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shcategory',
            old_name='slug',
            new_name='shslug',
        ),
    ]
