# Generated by Django 3.2.3 on 2022-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_slug_shcategory_shslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shproduct',
            old_name='slug',
            new_name='shslug',
        ),
    ]
