# Generated by Django 3.2.3 on 2022-05-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_slug_shproduct_shslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shproduct',
            name='shcategory',
        ),
        migrations.DeleteModel(
            name='ShCart',
        ),
        migrations.DeleteModel(
            name='ShCategory',
        ),
        migrations.DeleteModel(
            name='ShProduct',
        ),
    ]
