# Generated by Django 3.2.3 on 2022-05-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_msproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msproduct',
            name='song',
        ),
    ]
