# Generated by Django 3.2.3 on 2022-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20220520_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30, verbose_name='Music show')),
                ('source', models.CharField(max_length=30, verbose_name='location')),
                ('dest', models.CharField(max_length=30, verbose_name='language')),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
