# Generated by Django 3.2.3 on 2022-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_store',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product Image')),
                ('record', models.FileField(upload_to='product')),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=150, verbose_name='Concept'),
        ),
    ]
