# Generated by Django 3.2.3 on 2022-06-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_book_tot_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tot_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
